---
substitutions:
  device_format: ${ ["EU", "US"] | random }
  gang_count: ${ [1, 2, 3, 4] | random }

packages:
  common: !include common.yaml
  core_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_core.yaml
  standard_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_standard.yaml

bluetooth_proxy:
...
