---
packages:
  common_idf: !include common_idf.yaml
  core_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_core.yaml
  hw_relays_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_hw_relays.yaml
...
