---
substitutions:
  device_format: ${ ["EU", "US"] | random }
  gang_count: ${ [1, 2, 3, 4] | random }

packages:
  common_arduino: !include common_ard.yaml
  core_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_core.yaml
  hw_speaker_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_hw_speaker.yaml
...
