---
substitutions:
  model: US
  gangs: 4

packages:
  common_idf: !include common_idf.yaml
  core_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_core.yaml
  hw_vibration_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_hw_vibration.yaml
...
